### ISSUE TITLE
examples\basic_thread_border_router> idf.py build = basic_thread_border_router/build/esp-idf/main/spiffs_image/ot_rcp_0/rcp_image"FAILED (TZ-640)

### ISSUE THREAD

**Issue by Klippenhopper** [espressif/esp-thread-br#59]
PS C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-thread-br\examples\basic_thread_border_router> idf.py build
Executing action: all (aliases: build)
Running ninja in directory C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-thread-br\examples\basic_thread_border_router\build
Executing "ninja all"...
[5/1267] cmd.exe /C "cd /D C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-thread-br\examp...s/basic_thread_border_router/build/esp-idf/main/spiffs_image/ot_rcp_0/rcp_image"FAILED: esp-idf/main/CMakeFiles/rcp_image_generation C:/Users/Klipp/esp/v5.1.2/esp-idf/esp-thread-br/examples/basic_thread_border_router/build/esp-idf/main/CMakeFiles/rcp_image_generation
cmd.exe /C "cd /D C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-thread-br\examples\basic_thread_border_router\build\esp-idf\main && C:\Espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe C:/Users/Klipp/esp/v5.1.2/esp-idf/esp-thread-br/examples/basic_thread_border_router/main/../create_ota_image.py --rcp-build-dir C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-idf/examples/openthread/ot_rcp/build --target-file C:/Users/Klipp/esp/v5.1.2/esp-idf/esp-thread-br/examples/basic_thread_border_router/build/esp-idf/main/spiffs_image/ot_rcp_0/rcp_image"
Traceback (most recent call last):
  File "C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-thread-br\examples\basic_thread_border_router\create_ota_image.py", line 94, in <module>
    main()
  File "C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-thread-br\examples\basic_thread_border_router\create_ota_image.py", line 81, in main
    fout, FILETAG_RCP_FIRMWARE, os.path.getsize(rcp_firmware_path), offset)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 50, in getsize
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Users\\Klipp\\esp\\v5.1.2\\esp-idf\\esp-idf/examples/openthread/ot_rcp/build\\esp_ot_rcp.bin'
[8/1267] Generating ../../partition_table/partition-table.binPartition table binary generated. Contents:
*******************************************************************************
# ESP-IDF Partition Table
# Name, Type, SubType, Offset, Size, Flags
nvs,data,nvs,0x9000,24K,
otadata,data,ota,0xf000,8K,
phy_init,data,phy,0x11000,4K,
ota_0,app,ota_0,0x20000,1600K,
ota_1,app,ota_1,0x1b0000,1600K,
web_storage,data,spiffs,0x340000,100K,
rcp_fw,data,spiffs,0x359000,640K,
*******************************************************************************
**[14/1267] Building C object esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedtls.dir/ssl_cache.c.objninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-thread-br\examples\basic_thread_border_router\build\log\idf_py_stderr_output_8540 and C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-thread-br\examples\basic_thread_border_router\build\log\idf_py_stdout_output_8540**

Didn't found a open or closed issue with the same Problem....

Done everything like:
https://openthread.io/guides/border-router/espressif-esp32?hl=de

Till bolded worked fine:

cd esp-thread-br/examples/basic_thread_border_router
idf.py set-target esp32s3
**idf.py build**

Thx in advance

**Comment by Klippenhopper** [comment]
Ok,

found data here:
C:\Users\Klipp\esp\v5.1.2\esp-idf\examples\openthread\ot_rcp\

copied:

C:\Users\Klipp\esp\v5.1.2\esp-idf\examples\openthread\

to:
#
C:\Users\Klipp\esp\v5.1.2\esp-idf\esp-idf/examples/

and this Failure was gone.
